@echo off
setlocal EnableExtensions EnableDelayedExpansion

echo ========================================
echo Chatlog Wails Build Script
echo ========================================
echo.

set ICON_SRC=build\appicon.png
set ICON_TARGET=build\windows\icon.ico
set OUTPUT=build\bin\chatlog.exe
set WAILS_CMD=

rem Generate icon.ico (magick first, python+pillow fallback)
if exist "%ICON_SRC%" (
    if not exist "build\windows" mkdir "build\windows"
    set ICON_DONE=

    where magick >nul 2>&1
    if not errorlevel 1 (
        magick "!ICON_SRC!" -trim +repage -background none -gravity center -extent "%%[fx:max(w,h)]x%%[fx:max(w,h)]" -define icon:auto-resize=256,128,64,48,32,24,16 "!ICON_TARGET!" >nul 2>&1
        if not errorlevel 1 (
            set ICON_DONE=1
            echo [OK] icon generated by magick: !ICON_TARGET!
        )
    )

    if "!ICON_DONE!"=="" (
        where python >nul 2>&1
        if not errorlevel 1 (
            python -c "from PIL import Image; img=Image.open(r'!ICON_SRC!').convert('RGBA'); alpha=img.getchannel('A'); box=alpha.getbbox(); img=img.crop(box) if box else img; w,h=img.size; side=max(w,h); canvas=Image.new('RGBA',(side,side),(0,0,0,0)); canvas.paste(img,((side-w)//2,(side-h)//2),img); sizes=[(256,256),(128,128),(64,64),(48,48),(32,32),(24,24),(16,16)]; canvas.save(r'!ICON_TARGET!', format='ICO', sizes=sizes)" >nul 2>&1
            if not errorlevel 1 (
                set ICON_DONE=1
                echo [OK] icon generated by python: !ICON_TARGET!
            )
        )
    )

    if "!ICON_DONE!"=="" (
        echo [WARN] icon generation skipped, keep existing icon.ico
        echo [INFO] install ImageMagick: scoop install imagemagick
        echo [INFO] or install Pillow: python -m pip install pillow
    )
) else (
    echo [WARN] icon source not found: %ICON_SRC%
)

echo.
echo Detecting wails command...

where wails >nul 2>&1
if not errorlevel 1 set WAILS_CMD=wails

if "!WAILS_CMD!"=="" (
    if exist "%USERPROFILE%\go\bin\wails.exe" set WAILS_CMD=%USERPROFILE%\go\bin\wails.exe
)

if "!WAILS_CMD!"=="" (
    echo Installing wails CLI...
    go install github.com/wailsapp/wails/v2/cmd/wails@latest >nul 2>&1
    if exist "%USERPROFILE%\go\bin\wails.exe" set WAILS_CMD=%USERPROFILE%\go\bin\wails.exe
)

if "!WAILS_CMD!"=="" (
    echo [ERROR] wails command not found
    echo [INFO] ensure Go is installed and %%USERPROFILE%%\go\bin is in PATH
    goto :end
)

echo.
echo Running: !WAILS_CMD! build -clean -ldflags "-H windowsgui"
"!WAILS_CMD!" build -clean -ldflags "-H windowsgui"
if errorlevel 1 goto :build_fail

echo.
echo ========================================
echo [OK] Wails build succeeded
echo ========================================
echo Output: %OUTPUT%

if exist "%OUTPUT%" (
    for %%A in ("%OUTPUT%") do echo Size: %%~zA bytes

    echo.
    echo Trying UPX compression...
    where upx >nul 2>&1
    if not errorlevel 1 (
        upx --best --lzma "%OUTPUT%"
        if not errorlevel 1 (
            echo [OK] UPX compression succeeded
            for %%A in ("%OUTPUT%") do echo Compressed size: %%~zA bytes
        ) else (
            echo [WARN] UPX compression failed, keep original binary
        )
    ) else (
        echo [INFO] UPX not found, skip compression
    )
) else (
    echo [WARN] output file not found: %OUTPUT%
)

goto :end

:build_fail
echo.
echo ========================================
echo [ERROR] Wails build failed
echo ========================================
echo Exit code: %ERRORLEVEL%

:end
echo.
pause
endlocal
