// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wechatdb} from '../models';
import {main} from '../models';

export function Decrypt():Promise<void>;

export function DeleteAIProvider(arg1:string):Promise<void>;

export function EnableLogEvents(arg1:boolean):Promise<void>;

export function EnableStateEvents(arg1:boolean):Promise<void>;

export function GetContacts(arg1:string,arg2:number,arg3:number,arg4:number):Promise<wechatdb.GetContactsResp>;

export function GetDataKey():Promise<string>;

export function GetImgKey():Promise<string>;

export function GetKeys():Promise<Record<string, string>>;

export function GetLogPath():Promise<string>;

export function GetState():Promise<main.State>;

export function GetWebhookConfig():Promise<main.WebhookConfig>;

export function ListAIModels(arg1:main.AIProvider):Promise<Array<string>>;

export function ListAIProviders():Promise<Array<main.AIProvider>>;

export function ListInstances():Promise<Array<main.Instance>>;

export function ListListenIPs():Promise<Array<string>>;

export function ReadLogTail(arg1:number):Promise<string>;

export function Refresh():Promise<main.State>;

export function SaveAIProvider(arg1:main.AIProvider):Promise<main.AIProvider>;

export function SetAutoDecrypt(arg1:boolean):Promise<void>;

export function SetDataDir(arg1:string):Promise<main.State>;

export function SetDataKey(arg1:string):Promise<main.State>;

export function SetHTTPAddr(arg1:string):Promise<main.State>;

export function SetImgKey(arg1:string):Promise<main.State>;

export function SetWebhookConfig(arg1:main.WebhookConfig):Promise<void>;

export function SetWorkDir(arg1:string):Promise<main.State>;

export function StartHTTP():Promise<void>;

export function StopHTTP():Promise<void>;

export function SwitchToHistory(arg1:string):Promise<main.State>;

export function SwitchToPID(arg1:number):Promise<main.State>;

export function TestAIProvider(arg1:main.AIProvider):Promise<main.AITestResult>;
