// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Decrypt() {
  return window['go']['main']['App']['Decrypt']();
}

export function DeleteAIProvider(arg1) {
  return window['go']['main']['App']['DeleteAIProvider'](arg1);
}

export function EnableLogEvents(arg1) {
  return window['go']['main']['App']['EnableLogEvents'](arg1);
}

export function EnableStateEvents(arg1) {
  return window['go']['main']['App']['EnableStateEvents'](arg1);
}

export function GetContacts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetContacts'](arg1, arg2, arg3, arg4);
}

export function GetDataKey() {
  return window['go']['main']['App']['GetDataKey']();
}

export function GetImgKey() {
  return window['go']['main']['App']['GetImgKey']();
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetWebhookConfig() {
  return window['go']['main']['App']['GetWebhookConfig']();
}

export function ListAIModels(arg1) {
  return window['go']['main']['App']['ListAIModels'](arg1);
}

export function ListAIProviders() {
  return window['go']['main']['App']['ListAIProviders']();
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListListenIPs() {
  return window['go']['main']['App']['ListListenIPs']();
}

export function ReadLogTail(arg1) {
  return window['go']['main']['App']['ReadLogTail'](arg1);
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function SaveAIProvider(arg1) {
  return window['go']['main']['App']['SaveAIProvider'](arg1);
}

export function SetAutoDecrypt(arg1) {
  return window['go']['main']['App']['SetAutoDecrypt'](arg1);
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}

export function SetDataKey(arg1) {
  return window['go']['main']['App']['SetDataKey'](arg1);
}

export function SetHTTPAddr(arg1) {
  return window['go']['main']['App']['SetHTTPAddr'](arg1);
}

export function SetImgKey(arg1) {
  return window['go']['main']['App']['SetImgKey'](arg1);
}

export function SetWebhookConfig(arg1) {
  return window['go']['main']['App']['SetWebhookConfig'](arg1);
}

export function SetWorkDir(arg1) {
  return window['go']['main']['App']['SetWorkDir'](arg1);
}

export function StartHTTP() {
  return window['go']['main']['App']['StartHTTP']();
}

export function StopHTTP() {
  return window['go']['main']['App']['StopHTTP']();
}

export function SwitchToHistory(arg1) {
  return window['go']['main']['App']['SwitchToHistory'](arg1);
}

export function SwitchToPID(arg1) {
  return window['go']['main']['App']['SwitchToPID'](arg1);
}

export function TestAIProvider(arg1) {
  return window['go']['main']['App']['TestAIProvider'](arg1);
}
